# Generated by Django 5.0.4 on 2024-04-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id_cat', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('breed', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id_dog', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('breed', models.CharField(max_length=100)),
            ],
        ),
    ]
