# Generated by Django 5.0.4 on 2024-04-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='height',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='cat',
            name='width',
            field=models.IntegerField(default=400),
        ),
    ]
