# Generated by Django 5.0.4 on 2024-04-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_cat_height_cat_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
