# Generated by Django 5.0.4 on 2024-04-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_cat_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='id_cat',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
