# Generated by Django 4.2.11 on 2024-04-06 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_cat_id_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='name',
            field=models.URLField(default='null'),
        ),
        migrations.AddField(
            model_name='cat',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
