# Generated by Django 4.2.11 on 2024-04-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_cat_name_cat_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dogs',
        ),
    ]
